[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.2.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "9.0.0"

[[constraint]]
  name = "k8s.io/helm"
  version = "2.11.0"

[prune]
  go-tests = true
  unused-packages = true
